// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : dut.v
// Top        : BaseSoC
// Device     : sim
// Hierarchy  : disabled
// LiteX sha1 : 498d1fe82
// Date       : 2026-04-13 11:37:18
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module dut (
    input  wire          clk,
    input  wire   [31:0] fifo_dat_rx,
    output wire   [31:0] fifo_dat_tx,
    input  wire          fifo_stb_rx,
    input  wire          fifo_stb_tx,
    output wire          fifo_wait_rx,
    output wire          fifo_wait_tx,
    input  wire          reset,
    input  wire          sim_trace,
    input  wire    [5:0] sram_adr,
    output wire   [31:0] sram_dat_r,
    input  wire   [31:0] sram_dat_w,
    input  wire          sram_we,
    output wire          wishbone_ack,
    input  wire   [29:0] wishbone_adr,
    input  wire    [1:0] wishbone_bte,
    input  wire    [2:0] wishbone_cti,
    input  wire          wishbone_cyc,
    output wire   [31:0] wishbone_dat_r,
    input  wire   [31:0] wishbone_dat_w,
    output wire          wishbone_err,
    input  wire    [3:0] wishbone_sel,
    input  wire          wishbone_stb,
    input  wire          wishbone_we
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------

/*
BaseSoC
├── crg (_CRG)
├── bus (SoCBusHandler)
│    └── _interconnect (InterconnectShared)
│         ├── arbiter (Arbiter)
│         │    └── rr (RoundRobin)
│         ├── decoder (Decoder)
│         └── timeout (Timeout)
│              └── waittimer_0 (WaitTimer) [Gen]
├── csr (SoCCSRHandler)
├── irq (SoCIRQHandler)
├── ctrl (SoCController)
├── cpu (CPUNone)
├── sram (SRAM)
├── fifo (TestFIFOTransceiver)
│    ├── fifo_rx (SyncFIFO)
│    ├── fifo_tx (SyncFIFO)
│    └── fsm (FSM)
├── csr_bridge (Wishbone2CSR)
│    └── fsm (FSM)
├── csr_bankarray (CSRBankArray)
│    └── csrbank_0 (CSRBank) [Gen]
│         ├── csrstorage_0 (CSRStorage) [Gen]
│         ├── csrstorage_1 (CSRStorage) [Gen]
│         └── csrstatus_0 (CSRStatus) [Gen]
└── csr_interconnect (InterconnectShared)
Legend:
  [Gen]: Auto-generated instance name.
  [BB:NAME]: Blackbox instance (verilog Instance).

*/

//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire   [13:0] adr;
wire   [13:0] bank_bus_adr;
reg    [31:0] bank_bus_dat_r = 32'd0;
wire   [31:0] bank_bus_dat_w;
wire          bank_bus_re;
wire          bank_bus_we;
reg     [5:0] basesoc_adr = 6'd0;
reg           basesoc_adr_burst = 1'd0;
wire          basesoc_adr_burst_wrap;
reg    [29:0] basesoc_adr_counter = 30'd0;
wire   [29:0] basesoc_adr_counter_base;
reg     [3:0] basesoc_adr_counter_offset = 4'd0;
reg           basesoc_adr_latched = 1'd0;
wire   [29:0] basesoc_adr_next;
wire    [3:0] basesoc_adr_offset_lsb;
wire   [29:0] basesoc_adr_offset_msb;
wire          basesoc_bus_error;
reg    [31:0] basesoc_bus_errors = 32'd0;
reg           basesoc_bus_errors_re = 1'd0;
wire   [31:0] basesoc_bus_errors_status;
wire          basesoc_bus_errors_we;
wire          basesoc_cpu_rst;
wire   [31:0] basesoc_dat_r;
wire   [31:0] basesoc_dat_w;
reg           basesoc_ram_bus_ack = 1'd0;
wire   [29:0] basesoc_ram_bus_adr;
wire    [1:0] basesoc_ram_bus_bte;
wire    [2:0] basesoc_ram_bus_cti;
wire          basesoc_ram_bus_cyc;
wire   [31:0] basesoc_ram_bus_dat_r;
wire   [31:0] basesoc_ram_bus_dat_w;
reg           basesoc_ram_bus_err = 1'd0;
wire    [3:0] basesoc_ram_bus_sel;
wire          basesoc_ram_bus_stb;
wire          basesoc_ram_bus_we;
reg           basesoc_reset_re = 1'd0;
reg     [1:0] basesoc_reset_storage = 2'd0;
reg           basesoc_scratch_re = 1'd0;
reg    [31:0] basesoc_scratch_storage = 32'd305419896;
reg           basesoc_soc_rst = 1'd0;
reg     [3:0] basesoc_we = 4'd0;
reg           bus_ack = 1'd0;
wire   [29:0] bus_adr;
wire    [1:0] bus_bte;
wire    [2:0] bus_cti;
wire          bus_cyc;
reg    [31:0] bus_dat_r = 32'd0;
wire   [31:0] bus_dat_w;
reg           bus_err = 1'd0;
wire   [31:0] bus_errors_r;
reg           bus_errors_re = 1'd0;
wire   [31:0] bus_errors_w;
reg           bus_errors_we = 1'd0;
wire    [3:0] bus_sel0;
wire          bus_sel1;
wire          bus_stb;
wire          bus_we;
reg    [29:0] comb_self0 = 30'd0;
reg    [31:0] comb_self1 = 32'd0;
reg     [3:0] comb_self10 = 4'd0;
reg     [3:0] comb_self2 = 4'd0;
reg           comb_self3 = 1'd0;
reg           comb_self4 = 1'd0;
reg           comb_self5 = 1'd0;
reg     [2:0] comb_self6 = 3'd0;
reg     [1:0] comb_self7 = 2'd0;
reg     [3:0] comb_self8 = 4'd0;
reg     [3:0] comb_self9 = 4'd0;
reg    [19:0] count = 20'd1000000;
wire   [31:0] dat_r;
wire   [31:0] dat_w;
wire          done;
reg           error = 1'd0;
reg     [2:0] fifo_rx_consume = 3'd0;
wire          fifo_rx_do_read;
reg     [3:0] fifo_rx_level = 4'd0;
reg     [2:0] fifo_rx_produce = 3'd0;
wire    [2:0] fifo_rx_rdport_adr;
wire   [31:0] fifo_rx_rdport_dat_r;
reg           fifo_rx_replace = 1'd0;
wire   [31:0] fifo_rx_syncfifo_din;
wire   [31:0] fifo_rx_syncfifo_dout;
reg           fifo_rx_syncfifo_re = 1'd0;
wire          fifo_rx_syncfifo_readable;
wire          fifo_rx_syncfifo_we;
wire          fifo_rx_syncfifo_writable;
reg     [2:0] fifo_rx_wrport_adr = 3'd0;
wire   [31:0] fifo_rx_wrport_dat_r;
wire   [31:0] fifo_rx_wrport_dat_w;
wire          fifo_rx_wrport_we;
reg     [2:0] fifo_tx_consume = 3'd0;
wire          fifo_tx_do_read;
reg     [3:0] fifo_tx_level = 4'd0;
reg     [2:0] fifo_tx_produce = 3'd0;
wire    [2:0] fifo_tx_rdport_adr;
wire   [31:0] fifo_tx_rdport_dat_r;
reg           fifo_tx_replace = 1'd0;
reg    [31:0] fifo_tx_syncfifo_din = 32'd0;
wire   [31:0] fifo_tx_syncfifo_dout;
wire          fifo_tx_syncfifo_re;
wire          fifo_tx_syncfifo_readable;
reg           fifo_tx_syncfifo_we = 1'd0;
wire          fifo_tx_syncfifo_writable;
reg     [2:0] fifo_tx_wrport_adr = 3'd0;
wire   [31:0] fifo_tx_wrport_dat_r;
wire   [31:0] fifo_tx_wrport_dat_w;
wire          fifo_tx_wrport_we;
wire          grant;
reg           interface0_ack = 1'd0;
wire   [29:0] interface0_adr;
wire    [1:0] interface0_bte;
wire    [2:0] interface0_cti;
wire          interface0_cyc;
reg    [31:0] interface0_dat_r = 32'd0;
wire   [31:0] interface0_dat_w;
reg           interface0_err = 1'd0;
wire    [3:0] interface0_sel;
wire          interface0_stb;
wire          interface0_we;
reg    [13:0] interface1_adr = 14'd0;
wire   [31:0] interface1_dat_r;
reg    [31:0] interface1_dat_w = 32'd0;
reg           interface1_re = 1'd0;
reg           interface1_we = 1'd0;
reg           rd_ack = 1'd0;
wire          re;
wire          request;
wire    [1:0] reset0_r;
reg           reset0_re = 1'd0;
wire    [1:0] reset0_w;
reg           reset0_we = 1'd0;
wire   [31:0] scratch0_r;
reg           scratch0_re = 1'd0;
wire   [31:0] scratch0_w;
reg           scratch0_we = 1'd0;
wire          sel;
reg           shared_ack = 1'd0;
wire   [29:0] shared_adr;
wire    [1:0] shared_bte;
wire    [2:0] shared_cti;
wire          shared_cyc;
reg    [31:0] shared_dat_r = 32'd0;
wire   [31:0] shared_dat_w;
wire          shared_err;
wire    [3:0] shared_sel;
wire          shared_stb;
wire          shared_we;
wire          sim_wishbone_ack;
wire   [29:0] sim_wishbone_adr;
wire    [1:0] sim_wishbone_bte;
wire    [2:0] sim_wishbone_cti;
wire          sim_wishbone_cyc;
wire   [31:0] sim_wishbone_dat_r;
wire   [31:0] sim_wishbone_dat_w;
wire          sim_wishbone_err;
wire    [3:0] sim_wishbone_sel;
wire          sim_wishbone_stb;
wire          sim_wishbone_we;
reg     [2:0] slave_sel = 3'd0;
reg     [2:0] slave_sel_r = 3'd0;
wire    [5:0] sram_port_adr;
wire   [31:0] sram_port_dat_r;
wire   [31:0] sram_port_dat_w;
wire          sram_port_we;
reg     [3:0] sync_self = 4'd0;
wire          sys_clk;
wire          sys_rst;
reg     [1:0] testfifotransceiver_next_state = 2'd0;
reg     [1:0] testfifotransceiver_state = 2'd0;
wire          wait_1;
wire          we;
reg           wishbone2csr_next_state = 1'd0;
reg           wishbone2csr_state = 1'd0;
reg           wr_ack = 1'd0;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign sim_wishbone_adr = wishbone_adr;
assign wishbone_dat_r = sim_wishbone_dat_r;
assign sim_wishbone_dat_w = wishbone_dat_w;
assign sim_wishbone_sel = wishbone_sel;
assign sim_wishbone_cyc = wishbone_cyc;
assign sim_wishbone_stb = wishbone_stb;
assign wishbone_ack = sim_wishbone_ack;
assign sim_wishbone_we = wishbone_we;
assign sim_wishbone_cti = wishbone_cti;
assign sim_wishbone_bte = wishbone_bte;
assign wishbone_err = sim_wishbone_err;
assign sram_port_adr = sram_adr;
assign sram_port_dat_w = sram_dat_w;
assign sram_dat_r = sram_port_dat_r;
assign sram_port_we = sram_we;
assign basesoc_bus_error = error;
assign sys_clk = clk;
assign sys_rst = (~reset);
assign shared_adr = comb_self0;
assign shared_dat_w = comb_self1;
assign shared_sel = comb_self2;
assign shared_cyc = comb_self3;
assign shared_stb = comb_self4;
assign shared_we = comb_self5;
assign shared_cti = comb_self6;
assign shared_bte = comb_self7;
assign sim_wishbone_dat_r = shared_dat_r;
assign sim_wishbone_ack = (shared_ack & (grant == 1'd0));
assign sim_wishbone_err = (shared_err & (grant == 1'd0));
assign request = {sim_wishbone_cyc};
assign grant = 1'd0;
always @(*) begin
    slave_sel <= 3'd0;
    slave_sel[0] <= (shared_adr[29:6] == 21'd1048576);
    slave_sel[1] <= (shared_adr == 30'd872415232);
    slave_sel[2] <= (shared_adr[29:14] == 16'd57344);
end
assign basesoc_ram_bus_adr = shared_adr;
assign basesoc_ram_bus_dat_w = shared_dat_w;
assign basesoc_ram_bus_sel = shared_sel;
assign basesoc_ram_bus_stb = shared_stb;
assign basesoc_ram_bus_we = shared_we;
assign basesoc_ram_bus_cti = shared_cti;
assign basesoc_ram_bus_bte = shared_bte;
assign bus_adr = shared_adr;
assign bus_dat_w = shared_dat_w;
assign bus_sel0 = shared_sel;
assign bus_stb = shared_stb;
assign bus_we = shared_we;
assign bus_cti = shared_cti;
assign bus_bte = shared_bte;
assign interface0_adr = shared_adr;
assign interface0_dat_w = shared_dat_w;
assign interface0_sel = shared_sel;
assign interface0_stb = shared_stb;
assign interface0_we = shared_we;
assign interface0_cti = shared_cti;
assign interface0_bte = shared_bte;
assign basesoc_ram_bus_cyc = (shared_cyc & slave_sel[0]);
assign bus_cyc = (shared_cyc & slave_sel[1]);
assign interface0_cyc = (shared_cyc & slave_sel[2]);
always @(*) begin
    shared_ack <= 1'd0;
    shared_ack <= ((basesoc_ram_bus_ack | bus_ack) | interface0_ack);
    if (done) begin
        shared_ack <= 1'd1;
    end
end
assign shared_err = ((basesoc_ram_bus_err | bus_err) | interface0_err);
always @(*) begin
    shared_dat_r <= 32'd0;
    shared_dat_r <= ((({32{slave_sel_r[0]}} & basesoc_ram_bus_dat_r) | ({32{slave_sel_r[1]}} & bus_dat_r)) | ({32{slave_sel_r[2]}} & interface0_dat_r));
    if (done) begin
        shared_dat_r <= 32'd4294967295;
    end
end
assign wait_1 = ((shared_stb & shared_cyc) & (~shared_ack));
always @(*) begin
    error <= 1'd0;
    if (done) begin
        error <= 1'd1;
    end
end
assign done = (count == 1'd0);
assign basesoc_bus_errors_status = basesoc_bus_errors;
always @(*) begin
    basesoc_adr_burst <= 1'd0;
    case (basesoc_ram_bus_cti)
        2'd2: begin
            basesoc_adr_burst <= 1'd1;
        end
        3'd7: begin
            basesoc_adr_burst <= 1'd0;
        end
        default: begin
            basesoc_adr_burst <= 1'd0;
        end
    endcase
end
assign basesoc_adr_burst_wrap = (basesoc_ram_bus_bte[0] | basesoc_ram_bus_bte[1]);
assign basesoc_adr_counter_base = {basesoc_ram_bus_adr[29:4], (basesoc_ram_bus_adr & (~comb_self8))};
assign basesoc_adr_offset_lsb = ((basesoc_adr_counter + basesoc_adr_counter_offset) & comb_self9);
assign basesoc_adr_offset_msb = (basesoc_adr_counter & (~comb_self10));
assign basesoc_adr_next = (basesoc_adr_offset_msb + basesoc_adr_offset_lsb);
always @(*) begin
    basesoc_we <= 4'd0;
    basesoc_we[0] <= (((basesoc_ram_bus_cyc & basesoc_ram_bus_stb) & basesoc_ram_bus_we) & basesoc_ram_bus_sel[0]);
    basesoc_we[1] <= (((basesoc_ram_bus_cyc & basesoc_ram_bus_stb) & basesoc_ram_bus_we) & basesoc_ram_bus_sel[1]);
    basesoc_we[2] <= (((basesoc_ram_bus_cyc & basesoc_ram_bus_stb) & basesoc_ram_bus_we) & basesoc_ram_bus_sel[2]);
    basesoc_we[3] <= (((basesoc_ram_bus_cyc & basesoc_ram_bus_stb) & basesoc_ram_bus_we) & basesoc_ram_bus_sel[3]);
end
always @(*) begin
    basesoc_adr <= 6'd0;
    basesoc_adr <= basesoc_ram_bus_adr[5:0];
    if ((basesoc_adr_burst & basesoc_adr_latched)) begin
        basesoc_adr <= basesoc_adr_next[5:0];
    end
end
assign basesoc_ram_bus_dat_r = basesoc_dat_r;
assign basesoc_dat_w = basesoc_ram_bus_dat_w;
assign bus_sel1 = (bus_cyc & bus_stb);
always @(*) begin
    bus_ack <= 1'd0;
    if (bus_sel1) begin
        if (bus_we) begin
            bus_ack <= (wr_ack & bus_stb);
        end else begin
            bus_ack <= (rd_ack & bus_stb);
        end
    end else begin
        bus_ack <= 1'd0;
    end
end
assign fifo_rx_syncfifo_din = fifo_dat_rx;
assign fifo_wait_rx = fifo_rx_syncfifo_writable;
assign fifo_rx_syncfifo_we = fifo_stb_rx;
assign fifo_dat_tx = fifo_tx_syncfifo_dout;
assign fifo_wait_tx = fifo_tx_syncfifo_readable;
assign fifo_tx_syncfifo_re = fifo_stb_tx;
always @(*) begin
    fifo_rx_wrport_adr <= 3'd0;
    if (fifo_rx_replace) begin
        fifo_rx_wrport_adr <= (fifo_rx_produce - 1'd1);
    end else begin
        fifo_rx_wrport_adr <= fifo_rx_produce;
    end
end
assign fifo_rx_wrport_dat_w = fifo_rx_syncfifo_din;
assign fifo_rx_wrport_we = (fifo_rx_syncfifo_we & (fifo_rx_syncfifo_writable | fifo_rx_replace));
assign fifo_rx_do_read = (fifo_rx_syncfifo_readable & fifo_rx_syncfifo_re);
assign fifo_rx_rdport_adr = fifo_rx_consume;
assign fifo_rx_syncfifo_dout = fifo_rx_rdport_dat_r;
assign fifo_rx_syncfifo_writable = (fifo_rx_level != 4'd8);
assign fifo_rx_syncfifo_readable = (fifo_rx_level != 1'd0);
always @(*) begin
    fifo_tx_wrport_adr <= 3'd0;
    if (fifo_tx_replace) begin
        fifo_tx_wrport_adr <= (fifo_tx_produce - 1'd1);
    end else begin
        fifo_tx_wrport_adr <= fifo_tx_produce;
    end
end
assign fifo_tx_wrport_dat_w = fifo_tx_syncfifo_din;
assign fifo_tx_wrport_we = (fifo_tx_syncfifo_we & (fifo_tx_syncfifo_writable | fifo_tx_replace));
assign fifo_tx_do_read = (fifo_tx_syncfifo_readable & fifo_tx_syncfifo_re);
assign fifo_tx_rdport_adr = fifo_tx_consume;
assign fifo_tx_syncfifo_dout = fifo_tx_rdport_dat_r;
assign fifo_tx_syncfifo_writable = (fifo_tx_level != 4'd8);
assign fifo_tx_syncfifo_readable = (fifo_tx_level != 1'd0);
always @(*) begin
    testfifotransceiver_next_state <= 2'd0;
    testfifotransceiver_next_state <= testfifotransceiver_state;
    case (testfifotransceiver_state)
        1'd1: begin
            if ((bus_sel1 & (bus_cti == 1'd1))) begin
                testfifotransceiver_next_state <= 1'd1;
            end else begin
                testfifotransceiver_next_state <= 1'd0;
            end
        end
        2'd2: begin
            if ((bus_sel1 & (bus_cti == 1'd1))) begin
                testfifotransceiver_next_state <= 2'd2;
            end else begin
                testfifotransceiver_next_state <= 1'd0;
            end
        end
        default: begin
            if (bus_sel1) begin
                if (bus_we) begin
                    testfifotransceiver_next_state <= 2'd2;
                end else begin
                    testfifotransceiver_next_state <= 1'd1;
                end
            end
        end
    endcase
end
always @(*) begin
    fifo_tx_syncfifo_we <= 1'd0;
    case (testfifotransceiver_state)
        1'd1: begin
        end
        2'd2: begin
            if (fifo_tx_syncfifo_writable) begin
                fifo_tx_syncfifo_we <= 1'd1;
            end else begin
                fifo_tx_syncfifo_we <= 1'd0;
            end
        end
        default: begin
        end
    endcase
end
always @(*) begin
    fifo_rx_syncfifo_re <= 1'd0;
    case (testfifotransceiver_state)
        1'd1: begin
            if ((bus_sel1 & fifo_rx_syncfifo_readable)) begin
                fifo_rx_syncfifo_re <= 1'd1;
            end else begin
                fifo_rx_syncfifo_re <= 1'd0;
            end
        end
        2'd2: begin
        end
        default: begin
        end
    endcase
end
always @(*) begin
    bus_dat_r <= 32'd0;
    case (testfifotransceiver_state)
        1'd1: begin
            if ((bus_sel1 & fifo_rx_syncfifo_readable)) begin
                bus_dat_r <= fifo_rx_syncfifo_dout;
            end else begin
                bus_dat_r <= 32'd3735928559;
            end
        end
        2'd2: begin
        end
        default: begin
        end
    endcase
end
always @(*) begin
    fifo_tx_syncfifo_din <= 32'd0;
    case (testfifotransceiver_state)
        1'd1: begin
        end
        2'd2: begin
            fifo_tx_syncfifo_din <= bus_dat_w;
        end
        default: begin
        end
    endcase
end
always @(*) begin
    rd_ack <= 1'd0;
    case (testfifotransceiver_state)
        1'd1: begin
            if ((bus_sel1 & fifo_rx_syncfifo_readable)) begin
                rd_ack <= 1'd1;
            end else begin
                rd_ack <= 1'd0;
            end
        end
        2'd2: begin
        end
        default: begin
        end
    endcase
end
always @(*) begin
    wr_ack <= 1'd0;
    case (testfifotransceiver_state)
        1'd1: begin
        end
        2'd2: begin
            if (fifo_tx_syncfifo_writable) begin
                wr_ack <= 1'd1;
            end else begin
                wr_ack <= 1'd0;
            end
        end
        default: begin
        end
    endcase
end
always @(*) begin
    wishbone2csr_next_state <= 1'd0;
    wishbone2csr_next_state <= wishbone2csr_state;
    case (wishbone2csr_state)
        1'd1: begin
            wishbone2csr_next_state <= 1'd0;
        end
        default: begin
            if ((interface0_cyc & interface0_stb)) begin
                wishbone2csr_next_state <= 1'd1;
            end
        end
    endcase
end
always @(*) begin
    interface1_adr <= 14'd0;
    case (wishbone2csr_state)
        1'd1: begin
        end
        default: begin
            if ((interface0_cyc & interface0_stb)) begin
                interface1_adr <= interface0_adr;
            end
        end
    endcase
end
always @(*) begin
    interface1_re <= 1'd0;
    case (wishbone2csr_state)
        1'd1: begin
        end
        default: begin
            if ((interface0_cyc & interface0_stb)) begin
                interface1_re <= ((~interface0_we) & (interface0_sel != 1'd0));
            end
        end
    endcase
end
always @(*) begin
    interface1_we <= 1'd0;
    case (wishbone2csr_state)
        1'd1: begin
        end
        default: begin
            if ((interface0_cyc & interface0_stb)) begin
                interface1_we <= (interface0_we & (interface0_sel != 1'd0));
            end
        end
    endcase
end
always @(*) begin
    interface1_dat_w <= 32'd0;
    case (wishbone2csr_state)
        1'd1: begin
        end
        default: begin
            interface1_dat_w <= interface0_dat_w;
        end
    endcase
end
always @(*) begin
    interface0_dat_r <= 32'd0;
    case (wishbone2csr_state)
        1'd1: begin
            interface0_dat_r <= interface1_dat_r;
        end
        default: begin
        end
    endcase
end
always @(*) begin
    interface0_ack <= 1'd0;
    case (wishbone2csr_state)
        1'd1: begin
            interface0_ack <= 1'd1;
        end
        default: begin
        end
    endcase
end
assign sel = (bank_bus_adr[13:9] == 1'd0);
assign reset0_r = bank_bus_dat_w[1:0];
always @(*) begin
    reset0_re <= 1'd0;
    if ((sel & (bank_bus_adr[8:0] == 1'd0))) begin
        reset0_re <= bank_bus_we;
    end
end
always @(*) begin
    reset0_we <= 1'd0;
    if ((sel & (bank_bus_adr[8:0] == 1'd0))) begin
        reset0_we <= bank_bus_re;
    end
end
assign scratch0_r = bank_bus_dat_w;
always @(*) begin
    scratch0_we <= 1'd0;
    if ((sel & (bank_bus_adr[8:0] == 1'd1))) begin
        scratch0_we <= bank_bus_re;
    end
end
always @(*) begin
    scratch0_re <= 1'd0;
    if ((sel & (bank_bus_adr[8:0] == 1'd1))) begin
        scratch0_re <= bank_bus_we;
    end
end
assign bus_errors_r = bank_bus_dat_w;
always @(*) begin
    bus_errors_we <= 1'd0;
    if ((sel & (bank_bus_adr[8:0] == 2'd2))) begin
        bus_errors_we <= bank_bus_re;
    end
end
always @(*) begin
    bus_errors_re <= 1'd0;
    if ((sel & (bank_bus_adr[8:0] == 2'd2))) begin
        bus_errors_re <= bank_bus_we;
    end
end
always @(*) begin
    basesoc_soc_rst <= 1'd0;
    if (basesoc_reset_re) begin
        basesoc_soc_rst <= basesoc_reset_storage[0];
    end
end
assign basesoc_cpu_rst = basesoc_reset_storage[1];
assign reset0_w = basesoc_reset_storage;
assign scratch0_w = basesoc_scratch_storage;
assign bus_errors_w = basesoc_bus_errors_status;
assign basesoc_bus_errors_we = bus_errors_we;
assign adr = interface1_adr;
assign re = interface1_re;
assign we = interface1_we;
assign dat_w = interface1_dat_w;
assign interface1_dat_r = dat_r;
assign bank_bus_adr = adr;
assign bank_bus_re = re;
assign bank_bus_we = we;
assign bank_bus_dat_w = dat_w;
assign dat_r = bank_bus_dat_r;
always @(*) begin
    comb_self0 <= 30'd0;
    case (grant)
        default: begin
            comb_self0 <= sim_wishbone_adr;
        end
    endcase
end
always @(*) begin
    comb_self1 <= 32'd0;
    case (grant)
        default: begin
            comb_self1 <= sim_wishbone_dat_w;
        end
    endcase
end
always @(*) begin
    comb_self2 <= 4'd0;
    case (grant)
        default: begin
            comb_self2 <= sim_wishbone_sel;
        end
    endcase
end
always @(*) begin
    comb_self3 <= 1'd0;
    case (grant)
        default: begin
            comb_self3 <= sim_wishbone_cyc;
        end
    endcase
end
always @(*) begin
    comb_self4 <= 1'd0;
    case (grant)
        default: begin
            comb_self4 <= sim_wishbone_stb;
        end
    endcase
end
always @(*) begin
    comb_self5 <= 1'd0;
    case (grant)
        default: begin
            comb_self5 <= sim_wishbone_we;
        end
    endcase
end
always @(*) begin
    comb_self6 <= 3'd0;
    case (grant)
        default: begin
            comb_self6 <= sim_wishbone_cti;
        end
    endcase
end
always @(*) begin
    comb_self7 <= 2'd0;
    case (grant)
        default: begin
            comb_self7 <= sim_wishbone_bte;
        end
    endcase
end
always @(*) begin
    comb_self8 <= 4'd0;
    case (basesoc_ram_bus_bte)
        1'd0: begin
            comb_self8 <= 1'd0;
        end
        1'd1: begin
            comb_self8 <= 2'd3;
        end
        2'd2: begin
            comb_self8 <= 3'd7;
        end
        default: begin
            comb_self8 <= 4'd15;
        end
    endcase
end
always @(*) begin
    comb_self9 <= 4'd0;
    case (basesoc_ram_bus_bte)
        1'd0: begin
            comb_self9 <= 1'd0;
        end
        1'd1: begin
            comb_self9 <= 2'd3;
        end
        2'd2: begin
            comb_self9 <= 3'd7;
        end
        default: begin
            comb_self9 <= 4'd15;
        end
    endcase
end
always @(*) begin
    comb_self10 <= 4'd0;
    case (basesoc_ram_bus_bte)
        1'd0: begin
            comb_self10 <= 1'd0;
        end
        1'd1: begin
            comb_self10 <= 2'd3;
        end
        2'd2: begin
            comb_self10 <= 3'd7;
        end
        default: begin
            comb_self10 <= 4'd15;
        end
    endcase
end
always @(*) begin
    sync_self <= 4'd0;
    case (basesoc_ram_bus_bte)
        1'd0: begin
            sync_self <= 1'd0;
        end
        1'd1: begin
            sync_self <= 2'd3;
        end
        2'd2: begin
            sync_self <= 3'd7;
        end
        default: begin
            sync_self <= 4'd15;
        end
    endcase
end


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge sys_clk) begin
    slave_sel_r <= slave_sel;
    if (wait_1) begin
        if ((~done)) begin
            count <= (count - 1'd1);
        end
    end else begin
        count <= 20'd1000000;
    end
    if ((basesoc_bus_errors != 32'd4294967295)) begin
        if (basesoc_bus_error) begin
            basesoc_bus_errors <= (basesoc_bus_errors + 1'd1);
        end
    end
    if (((basesoc_ram_bus_cyc & basesoc_ram_bus_stb) & basesoc_adr_burst)) begin
        basesoc_adr_latched <= 1'd1;
        if (basesoc_adr_latched) begin
            basesoc_adr_counter <= (basesoc_adr_counter + 1'd1);
        end else begin
            basesoc_adr_counter_offset <= (basesoc_ram_bus_adr & sync_self);
            basesoc_adr_counter <= (basesoc_adr_counter_base + {{29{1'd0}}, (~basesoc_ram_bus_we)});
        end
        if ((basesoc_ram_bus_cti == 3'd7)) begin
            basesoc_adr_latched <= 1'd0;
            basesoc_adr_counter <= 1'd0;
            basesoc_adr_counter_offset <= 1'd0;
        end
    end else begin
        basesoc_adr_latched <= 1'd0;
        basesoc_adr_counter <= 1'd0;
        basesoc_adr_counter_offset <= 1'd0;
    end
    basesoc_ram_bus_ack <= 1'd0;
    if (((basesoc_ram_bus_cyc & basesoc_ram_bus_stb) & ((~basesoc_ram_bus_ack) | basesoc_adr_burst))) begin
        basesoc_ram_bus_ack <= 1'd1;
    end
    if (((fifo_rx_syncfifo_we & fifo_rx_syncfifo_writable) & (~fifo_rx_replace))) begin
        fifo_rx_produce <= (fifo_rx_produce + 1'd1);
    end
    if (fifo_rx_do_read) begin
        fifo_rx_consume <= (fifo_rx_consume + 1'd1);
    end
    if (((fifo_rx_syncfifo_we & fifo_rx_syncfifo_writable) & (~fifo_rx_replace))) begin
        if ((~fifo_rx_do_read)) begin
            fifo_rx_level <= (fifo_rx_level + 1'd1);
        end
    end else begin
        if (fifo_rx_do_read) begin
            fifo_rx_level <= (fifo_rx_level - 1'd1);
        end
    end
    if (((fifo_tx_syncfifo_we & fifo_tx_syncfifo_writable) & (~fifo_tx_replace))) begin
        fifo_tx_produce <= (fifo_tx_produce + 1'd1);
    end
    if (fifo_tx_do_read) begin
        fifo_tx_consume <= (fifo_tx_consume + 1'd1);
    end
    if (((fifo_tx_syncfifo_we & fifo_tx_syncfifo_writable) & (~fifo_tx_replace))) begin
        if ((~fifo_tx_do_read)) begin
            fifo_tx_level <= (fifo_tx_level + 1'd1);
        end
    end else begin
        if (fifo_tx_do_read) begin
            fifo_tx_level <= (fifo_tx_level - 1'd1);
        end
    end
    testfifotransceiver_state <= testfifotransceiver_next_state;
    wishbone2csr_state <= wishbone2csr_next_state;
    bank_bus_dat_r <= 1'd0;
    if (sel) begin
        case (bank_bus_adr[8:0])
            1'd0: begin
                bank_bus_dat_r <= reset0_w;
            end
            1'd1: begin
                bank_bus_dat_r <= scratch0_w;
            end
            2'd2: begin
                bank_bus_dat_r <= bus_errors_w;
            end
        endcase
    end
    if (reset0_re) begin
        basesoc_reset_storage <= reset0_r;
    end
    basesoc_reset_re <= reset0_re;
    if (scratch0_re) begin
        basesoc_scratch_storage <= scratch0_r;
    end
    basesoc_scratch_re <= scratch0_re;
    basesoc_bus_errors_re <= bus_errors_re;
    if (sys_rst) begin
        basesoc_reset_storage <= 2'd0;
        basesoc_reset_re <= 1'd0;
        basesoc_scratch_storage <= 32'd305419896;
        basesoc_scratch_re <= 1'd0;
        basesoc_bus_errors_re <= 1'd0;
        basesoc_bus_errors <= 32'd0;
        basesoc_ram_bus_ack <= 1'd0;
        basesoc_adr_latched <= 1'd0;
        basesoc_adr_counter <= 30'd0;
        basesoc_adr_counter_offset <= 4'd0;
        fifo_rx_level <= 4'd0;
        fifo_rx_produce <= 3'd0;
        fifo_rx_consume <= 3'd0;
        fifo_tx_level <= 4'd0;
        fifo_tx_produce <= 3'd0;
        fifo_tx_consume <= 3'd0;
        slave_sel_r <= 3'd0;
        count <= 20'd1000000;
        testfifotransceiver_state <= 2'd0;
        wishbone2csr_state <= 1'd0;
    end
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Memory sram: 64-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8
// Port 1 | Read: Sync  | Write: Sync | Mode: Write-First
reg [31:0] sram[0:63];
initial begin
	$readmemh("dut_sram.init", sram);
end
reg [5:0] sram_adr0;
reg [5:0] sram_adr1;
always @(posedge sys_clk) begin : mem_write_block
	integer we_index;
	for(we_index = 0; we_index < 4; we_index=we_index+1)
		if (basesoc_we[we_index])
			sram[basesoc_adr][we_index*8 +: 8] <= basesoc_dat_w[we_index*8 +: 8];
	sram_adr0 <= basesoc_adr;
end
always @(posedge sys_clk) begin
	if (sram_port_we)
		sram[sram_port_adr] <= sram_port_dat_w;
	sram_adr1 <= sram_port_adr;
end
assign basesoc_dat_r = sram[sram_adr0];
assign sram_port_dat_r = sram[sram_adr1];


//------------------------------------------------------------------------------
// Memory storage: 8-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Async | Write: ---- | 
reg [31:0] storage[0:7];
reg [31:0] storage_dat0;
always @(posedge sys_clk) begin
	if (fifo_rx_wrport_we)
		storage[fifo_rx_wrport_adr] <= fifo_rx_wrport_dat_w;
	storage_dat0 <= storage[fifo_rx_wrport_adr];
end
always @(posedge sys_clk) begin
end
assign fifo_rx_wrport_dat_r = storage_dat0;
assign fifo_rx_rdport_dat_r = storage[fifo_rx_rdport_adr];


//------------------------------------------------------------------------------
// Memory storage_1: 8-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Async | Write: ---- | 
reg [31:0] storage_1[0:7];
reg [31:0] storage_1_dat0;
always @(posedge sys_clk) begin
	if (fifo_tx_wrport_we)
		storage_1[fifo_tx_wrport_adr] <= fifo_tx_wrport_dat_w;
	storage_1_dat0 <= storage_1[fifo_tx_wrport_adr];
end
always @(posedge sys_clk) begin
end
assign fifo_tx_wrport_dat_r = storage_1_dat0;
assign fifo_tx_rdport_dat_r = storage_1[fifo_tx_rdport_adr];


endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2026-04-13 11:37:18.
//------------------------------------------------------------------------------
