ver = "0.4.1"

[[tests]]
name = "axis.tests_wal_advanced_axis.axis_monitor_uart_axi_AXIS"
paths = [
  "../../tests/wal/advanced/axis.prot",
]
expect_dir = "../../tests/wal/advanced/expects"
expect_name = "axis.monitor.uart_axi.AXIS.expect"
cmd = "cd ../.. && cargo run --offline --package protocols-monitor -- --protocol tests/wal/advanced/axis.prot --wave tests/wal/advanced/uart-axi.fst --instances uut_rx:AXIS --sample-posedge uut_rx.clk --show-waveform-time --time-unit ns 2>/dev/null"

[[tests]]
name = "axis.tests_wal_advanced_axis_failing.axis_failing_monitor_uart_axi_minimal_AXIS"
paths = [
  "../../tests/wal/advanced/axis_failing.prot",
]
expect_dir = "../../tests/wal/advanced/expects"
expect_name = "axis_failing.monitor.uart_axi_minimal.AXIS.expect"
cmd = "cd ../.. && cargo run --offline --package protocols-monitor -- --protocol tests/wal/advanced/axis_failing.prot --wave tests/wal/advanced/uart-axi-minimal.fst --instances uut_rx:AXIS --sample-posedge uut_rx.clk --show-waveform-time --time-unit ns 2>/dev/null"

[[tests]]
name = "axis.tests_wal_advanced_axis_minimal.axis_minimal_monitor_uart_axi_minimal_AXIS"
paths = [
  "../../tests/wal/advanced/axis_minimal.prot",
]
expect_dir = "../../tests/wal/advanced/expects"
expect_name = "axis_minimal.monitor.uart_axi_minimal.AXIS.expect"
cmd = "cd ../.. && cargo run --offline --package protocols-monitor -- --protocol tests/wal/advanced/axis_minimal.prot --wave tests/wal/advanced/uart-axi-minimal.fst --instances uut_rx:AXIS --sample-posedge uut_rx.clk --show-waveform-time --time-unit ns 2>/dev/null"

[[tests]]
name = "axis.tests_wal_advanced_axis_truncated.axis_truncated_monitor_uart_axi_truncated_AXIS"
paths = [
  "../../tests/wal/advanced/axis_truncated.prot",
]
expect_dir = "../../tests/wal/advanced/expects"
expect_name = "axis_truncated.monitor.uart_axi_truncated.AXIS.expect"
cmd = "cd ../.. && cargo run --offline --package protocols-monitor -- --protocol tests/wal/advanced/axis_truncated.prot --wave tests/wal/advanced/uart-axi-truncated.fst --instances uut_rx:AXIS --sample-posedge uut_rx.clk --show-waveform-time --time-unit ns 2>/dev/null"

[[tests]]
name = "axis.tests_wal_advanced_axis_truncated_include_idle.axis_truncated_include_idle_monitor_uart_axi_truncated_AXIS"
paths = [
  "../../tests/wal/advanced/axis_truncated_include_idle.prot",
]
expect_dir = "../../tests/wal/advanced/expects"
expect_name = "axis_truncated_include_idle.monitor.uart_axi_truncated.AXIS.expect"
cmd = "cd ../.. && cargo run --offline --package protocols-monitor -- --protocol tests/wal/advanced/axis_truncated_include_idle.prot --wave tests/wal/advanced/uart-axi-truncated.fst --instances uut_rx:AXIS --sample-posedge uut_rx.clk --show-waveform-time --time-unit ns --include-idle 2>/dev/null"
